language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
script:
- ./gradlew ":library:build"
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: hygb+GgQVqQEi0RfbV2whSxeRBYy6b3NGMrBWY7VFagImBSxkEi54TjVwcCIo78ACmnwy9x+yjEV2s/FVYKYR/znooO43jjh4xMhbTUDAD9bBQnRI+Kcefci0FKX40Pbvj9m7nuucTznkpvHjKYbGmmp2z+qinSe3Q1gtu32gb3lLqzGnn2U6fIW9K+5ezIB4dYs1ZR+/oYuYzrO7MpwzGwhCu0LBbIMyOpI/p+p/dK4VZyV1oltgAwZZEbhzMMtbuEcbOEN+oqUJAQJXBRQnNfItP1yXLP4zbNKkksr+hojbAM/CxHFsIZJ/PnevT0x0eGkaK4avpJ445RfB+VLOeAxgHO1O7B0VpVc+G+e2AG1e0ImTlG8eWszYPHXGAwnzzT3Ps14H2HyxZVFbqWNQeS3sEwAOH18SiJCqpIv2iF2yIFoQp/pF9xlWmwxbjMI7ipX3zP5HKx6sGz5PgPzh4hQ5yAGzWU57D4kr/RcK+rOE957UbN7q83VyKTrLIOUJ0mHunl3Mf4kP2kshRNm/d7rB4P8VEuzkII8JzuVW2Y640myl8JLUlLdaDksSRRFb/9ENedZoOmf6WkElrbypSCV2+ImEA1qsFdKxR2QECfedX9gncx6kibrRJRybQcn+exQTXhP3YTLEuc2pJBZHb4SXcjFTEXw+fV00TGEBgw=
  - secure: MC2ypr05oIZLHUYj8ZkHeZ4chvdBJQs4UvkOBU0GI5CR9VpEuX1GH6vi1oIvlqXJ65vJCT9gq2BDUKmjP6GCLtRBM/hoR0nhGSvWmCOTeGuYWjI4JjpMUV81WvtX9353YKj6DK24pAbK9On4I7iGfRpLZJhu5XVAY9DpgFnHJxnr+fNJK8p92WbfsYQa6dR4KkIpDk3fLAdniEipvwKjwaEpMsDo82g34lCIRKJ5mKxu/gtv5rVkjOGkCUbIt2BpoANoB/sqOr+vW9/PbGspw8PeUPUtAW0o5bcRhrjI6Kop3HwO4OuQN2Hups5lf4sTJUEW0AOi+vyjkNFuVk2mCIbkPSeSBUp0HaDuo5FdhXrx03n2ph7WP9df+2P0gyNACA4UMZa9KahERZtsiq8lOL3U8IN0Ui8tUcqc8xiArsu2Ie/th9P2RSHmtkgtIBVjaN2x+HEO7OpMnnbTfZJHNDmGjqCDY/VTFN/343FN24oybNo+VPTMBXDjDvMbV+WT6bQOM3XpadHhm+laBZADl651zcgtgf/HpqoDGlaPCESeYTyewdRvx9xLYmi+1ty320oAmuvrquTDB6Ig6DQDlG5oVgczgJ5vkXvqWYYbixWX8SSTigX4xrtBM8GoANZItN19VN2RDPfpiPO2Eiy9Y+M6xRrzWB7+EOwm1QH29do=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
